baseURL = "http://abhinavmir.github.io/"
languageCode = "en-us"
title = "Computerra"
theme = "notrack"
newContentEditor = "nvim"
mainSections = ["blog"]
# disqusShortname = "example"
paginate = 4

[params]
  author = "Hugo de Groot"
  siteHeading = "Abhinav / August" # defaults to author
  favicon = "hugo_grotius.png" # Adds a small icon next to the page title in a tab
  showBlogLatest = true
  mainSections = ["blog"]
  showTaxonomyLinks = false
  nBlogLatest = 4 # number of blog post om the home page
  blogLatestHeading = "Fresh from the oven"

  [params.social]
    github = "abhinavmir"
    linkedin = "abhinavmir"
    email = "sabhinav@bu.edu"
    mastodon = "ioc.exchange/@formalcurryfication"
    rss = "rss won't use the value you give it so you can put anything here"
    keybase = "example"

[taxonomies]
  year = "year"
  month = "month"
  tags = "tags"
  categories = "categories"

[permalinks]
  blog = "/blog/:year/:month/:slug"
