baseurl: "/"
languageCode: "en-us"
title: "Abhinav's Blog"
theme: "hugo-xmin"
googleAnalytics: ""
disqusShortname: ""
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$"]
footnotereturnlinkcontents: "↩"

permalinks:
  note: "/note/:year/:month/:day/:slug/"
  post: "/post/:year/:month/:day/:slug/"

menu:
  main:
    - name: Home
      url: ""
      weight: 1
    - name: Research
      url: "research/"
      weight: 2

params:
  description: "A website built through Hugo and blogdown."
  footer: "&copy; Abhinav Sriavstava"

markup:
  highlight:
    codeFences: false
  goldmark:
    renderer:
      unsafe: true
