name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Set your default branch here

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Set your Python version here

    - name: Install dependencies
      run: |
        pip install fastapi uvicorn gunicorn jinja2 markdown2
        # Add any other dependencies you might have

    - name: Build and Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public  # Set the directory to deploy
